CREATE TABLE IF NOT EXISTS uav (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL,
  model VARCHAR(128) NOT NULL,
  manufacturer VARCHAR(128) NOT NULL,
  max_flight_time_minutes INT,
  max_range_km INT,
  payload_kg INT,
  max_altitude_meters INT,
  max_speed_kmh INT,
  battery_capacity_mah INT,
  weight_kg DECIMAL(10,2),
  camera_resolution VARCHAR(64),
  has_gps TINYINT(1) DEFAULT 0,
  has_obstacle_avoidance TINYINT(1) DEFAULT 0,
  purchase_date DATE,
  warranty_expire_date DATE,
  serial_number VARCHAR(128),
  department VARCHAR(128),
  application_field VARCHAR(128),
  status VARCHAR(32) NOT NULL,
  remark VARCHAR(512),
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  UNIQUE KEY uk_uav_code (code)
);