CREATE TABLE IF NOT EXISTS uav (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL,
  model TEXT NOT NULL,
  manufacturer TEXT NOT NULL,
  max_flight_time_minutes INTEGER,
  max_range_km INTEGER,
  payload_kg INTEGER,
  max_altitude_meters INTEGER,
  max_speed_kmh INTEGER,
  battery_capacity_mah INTEGER,
  weight_kg REAL,
  camera_resolution TEXT,
  has_gps INTEGER DEFAULT 0,
  has_obstacle_avoidance INTEGER DEFAULT 0,
  purchase_date TEXT,
  warranty_expire_date TEXT,
  serial_number TEXT,
  department TEXT,
  application_field TEXT,
  status TEXT NOT NULL,
  remark TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (code)
);